---
version: 2
updates:

  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
      time: '20:01'
    target-branch: main

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '20:01'
    target-branch: main
