name: Build
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: Perform base checks
        run: ./gradlew app:assembleDebug library:sourcesJar library:dokkaJar --stacktrace
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: Execute unit tests
        run: ./gradlew library:testDebugUnitTest --stacktrace
  ANDROID_BUILD_APK:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'

      - name: Execute APK build
        run: ./gradlew app:assembleDebug --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: apk-files
          path: app/build/outputs/apk/**/*.apk
